# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up keychain and import certificate
        env:
          CERTIFICATE_PASSWORD: ${{ secrets.MAC_DEV_CERTIFICATE_PASSWORD }}

        run: |
            # Create and configure a temporary keychain
            security create-keychain -p "" build.keychain
            security default-keychain -s build.keychain
            security unlock-keychain -p "" build.keychain

            # Decode the certificate from the secret and save it as a file
            echo "${{ secrets.MAC_DEV_CERTIFICATE_BASE64 }}" | base64 --decode > certificate.p12

            # Import the certificate into the keychain
            security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign

            # List keychains (optional) to verify your build.keychain is active
            security list-keychains -d user
      
      - name: Set Xcode version to Xcode 15
        run: sudo xcode-select -s /Applications/Xcode_16.2.0.app/Contents/Developer
      
      - name: Verify Xcode version
        run: xcodebuild -version

      - name: Build with xcodebuild
        run: xcodebuild -project "GPU Deals.xcodeproj" -scheme "GPU Deals" -destination 'platform=macOS' build

      - name: Run tests with xcodebuild
        run: xcodebuild -project "GPU Deals.xcodeproj" -scheme "GPU Deals" -destination 'platform=macOS' test
